name: mir-kiosk
version: mir
version-script: |
    LANG=C apt-cache policy mir-demos | sed -rne 's/^\s+Candidate:\s+(.*)-[^-]+$/\1/p'
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
grade: stable

slots:
  mir-libs-1604:
    interface: content
    content: mir0-1604
    read: [usr/lib]

  wayland-socket-dir:
    interface: content
    content: wayland-socket-dir
    write: [ $SNAP_DATA/wayland ]

apps:
  mir-kiosk:
    command: bin/run-miral
    daemon: simple
    slots:
      - mir
      - wayland
    plugs:
      - opengl
    environment:
      # Share the wayland sockets via content interface, so place in dedicated directory
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/arm-linux-gnueabihf/dri:/var/lib/snapd/lib/gl/xorg
      LD_LIBRARY_PATH: $SNAP/usr/lib/qemu:$SNAP/usr/lib/arm-linux-gnueabihf/mesa:$SNAP/usr/lib/arm-linux-gnueabihf/mesa-egl:$SNAP/usr/lib/arm-linux-gnueabihf/dri:/var/lib/snapd/lib/gl/xorg:$SNAP/usr/lib/arm-linux-gnueabihf/pulseaudio:$LD_LIBRARY_PATH
      XDG_RUNTIME_DIR: $SNAP_DATA/wayland
      XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
      XCURSOR_PATH:    $SNAP/icons

parts:
  mir:
    plugin: nil
    stage-packages:
      - mir-graphics-drivers-desktop
      - mir-demos

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    organize:
      usr/share/icons/DMZ-White: icons/default
    prime:
     - icons/default

  glue:
    plugin: dump
    source: glue
